name: Monthly job

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 1 * *'

jobs:
  monthly_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Google API Client Library
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client
          pip install beautifulsoup4

      - name: Run Yugioh Goods Parser
        env:
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
        run: |
          python yugioh_goods_parser.py
